### ISSUE TITLE
API version bump (1 - > 2)

### ISSUE THREAD

**Issue by staticssleever668** [libratbag/libratbag#1388]
:heavy_check_mark: - Good to go
:heavy_multiplication_x: - Rejected or needs a complete rewrite
:stop_sign: - Blocked on something else
:arrows_clockwise: - In process of reviewing
:question: - Unknown status

- Disabling resolutions
- [x] :heavy_check_mark: #870
- [x] :heavy_check_mark: https://github.com/libratbag/piper/pull/448
- Device type property (to allow remapping first two keys on keyboards)
TODO: remake these while adding a new device capabilities API. This should be done in another API version bump, for now these are good as-is.
- [x] :heavy_check_mark: #931
- [x] :heavy_check_mark: https://github.com/libratbag/piper/pull/536
- Disabling buttons
- [x] :heavy_check_mark: #953
- [x] :heavy_check_mark: https://github.com/libratbag/piper/pull/821
- Simple key bindings
- [x] :heavy_check_mark: #1368
- [x] :heavy_check_mark: https://github.com/libratbag/piper/pull/804
- [ ] :heavy_multiplication_x: #1470 #1471 (rejected: #1523)
- Firmware version
- [x] :heavy_check_mark: #1372
- Angle snapping and debounce time
- [x] :heavy_check_mark: #1394
- Other
- [ ] :thinking: Should ratbagd_api_version be split into major/minor version to more closely resemble semantic versioning?
This would allow for forward compatibility if we add something new but don't change anything old.
---

After merging all relevant PRs:

- [x] Update docs (#1523)
- [x] Check if all deprecated fields have been removed (#1430).

---

Potential problems:

Users of Piper from Flatpak may have an API version mismatch.
For some it will be unsolvable as some distros like older Ubuntu versions for example will never update libratbag.

Title: Incompatible ratbagd API version (required: 2, provided: 1) with Flatpak Piper

You have two options:
- Roll-back to an older Piper version
Run `flatpak update --commit=72e3fe60e8b4b404ae9a750882d57f0c29eecca131bd5b0b505c8f223f0e8796 org.freedesktop.Piper` (commit hash found with `flatpak remote-info --log flathub org.freedesktop.Piper`).
Then `flatpak mask org.freedesktop.Piper` to disable updates (`flatpak mask --remove org.freedesktop.Piper` to undo).
If you didn't have Piper before or uninstalled it, you may have to install a newer version first and only then rollback.
- Use Piper from you distro's repo. 

TODO: make a PR with new version on https://github.com/flathub/org.freedesktop.Piper.

**Comment by staticssleever668** [comment]
OK, I decided to drop modifiers in single key bindings, as this can instead be accomplished with macros. With that in mind, we should be ready for a new release.
I'll open an issue on Piper side with solution to the "Incompatible ratbagd API version (required: 2, provided: 1)" problem.
